#!/bin/sh
# -----------------------------------------------------------------------------
# docker /start.sh script
# -----------------------------------------------------------------------------
if [ ! -d "/data/files" ]; then
  mkdir /data/files
  echo "Created Files Folder!"
fi

if [ -a /teamspeak/ts3server.sqlitedb ]; then
  echo "A"
  rm /teamspeak/ts3server.sqlitedb
  ln -s /data/ts3server.sqlitedb /teamspeak/ts3server.sqlitedb
fi

if [ -d /teamspeak/files ]; then
  echo "B"
  rm -r /teamspeak/files
  ln -s /data/files /teamspeak/files
fi

cd /teamspeak
if [ ! -s /teamspeak/query_ip_whitelist.txt ]; then
  echo "127.0.0.1" >> query_ip_whitelist.txt
  echo "172.0.0.0/8" >> query_ip_whitelist.txt
fi

exec /teamspeak/ts3server inifile=/data/ts3server.ini logpath=/data/logs disable_db_logging=0
